stages:
  - package

package:
  stage: package
  image: alpine:latest
  script:
    - apk add --update zip
    - cd src/frontend
    - zip frontend.zip ./*
  artifacts:
    name: "frontend-$CI_COMMIT_TAG"
    paths:
      - frontend.zip
  tags:
    - docker