stages:
  - package
  - deploy
  - swap

package:
  stage: package
  image: alpine:latest
  script:
    - apk add --update zip
    - mkdir dist
    - mv src/frontend/* dist
    - cd dist
    - zip frontend.zip ./*
  artifacts:
    name: "frontend"
    paths:
      - dist/frontend.zip
      - deploy.sh
  tags:
    - docker
    
deploy:
  stage: deploy
  script:
    - chmod 774 deploy.sh
    - ./deploy.sh
  variables:
    GIT_STRATEGY: none
  tags:
    - blue-green
    
swap:
  stage: swap
  script:
    - DEPLOYMENT_ENV=$(curl -s https://staging.notkimsereylam.xyz/deployment_id)
    - ssh notkl "sudo ln -s /etc/nginx/sites-available/$DEPLOYMENT_ENV /etc/nginx/sites-enabled/upstreams"
    - ssh notkl "sudo systemctl reload nginx"
  variables:
    GIT_STRATEGY: none
  when: manual
  tags:
    - blue-green